# Generated by Django 5.1.7 on 2025-07-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField()),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("receipe_pk", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "social_media",
                    models.CharField(
                        choices=[("facebook", "Facebook"), ("instagram", "Instagram")],
                        max_length=50,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("post", "Post"), ("reel", "Reel")],
                        default="post",
                        max_length=50,
                    ),
                ),
                (
                    "sound_track",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
        ),
    ]
