# Generated by Django 5.1.7 on 2025-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.IntegerField()),
                ("comment_id", models.IntegerField(unique=True)),
                ("comment", models.CharField(max_length=200)),
                ("replied", models.BooleanField(default=False)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("self_comment", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="socialpost",
            name="ai_caption",
            field=models.TextField(blank=True, default=""),
        ),
    ]
