# Generated by Django 5.1.7 on 2025-07-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_socialcomment_socialpost_ai_caption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialpost",
            name="receipe_pk",
        ),
        migrations.AddField(
            model_name="socialpost",
            name="post_identifier",
            field=models.CharField(blank=True, unique=True),
        ),
    ]
